version: '3'

services:

  hiperson:
    build: 
      context: ./www
      dockerfile: $PWD/docker/NodeJS/Dockerfile
    volumes:
      - ./www:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '19081:80'
    depends_on:
      - mariadb
  
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

volumes:
  hiperson: 
    driver: local
